# Certificate copied from cert-manager to avoid duplicate requests to acme server.
# Ref: https://github.com/mittwald/kubernetes-replicator
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.tlsCertificate.name }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ include "frontend.fullname" . }}
  annotations:
    replicator.v1.mittwald.de/replicate-from: {{ .Values.tlsCertificate.from }}
type: {{ .Values.tlsCertificate.type }}
data:
  tls.key: ""
  tls.crt: ""
  ca.crt: ""