apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: block-metrics
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "frontend.labels" . | nindent 4 }}
spec:
  plugin:
    blockpath:
      paths:
        - "^/metrics$"
