apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: {{ include "isso.fullname" . }}-headers
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "isso.labels" . | nindent 4 }}
spec:
  headers:
    customRequestHeaders:
      X-Script-Name: {{ .Values.config.scriptName }}
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: {{ include "isso.fullname" . }}-stripprefix
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "isso.labels" . | nindent 4 }}
spec:
  stripPrefix:
    prefixes:
      - {{ .Values.config.scriptName }}