apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: {{ .Values.middleware.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "frontend.labels" . | nindent 4 }}
spec:
  plugin:
    blockpath:
      paths:
        - "^/metrics$"
