apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: {{ .Values.middleware.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    checksum/config: 671e1053377e64a15661c2f98c1e21ee90819dc8
    {{- include "frontend.labels" . | nindent 4 }}
spec:
  plugin:
    # Ref: https://github.com/traefik/plugin-blockpath/tree/master
    blockpath:
      regex:
        - "^/metrics$"